# Generated by Django 6.0.4 on 2026-04-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('since_id', models.CharField(blank=True, help_text='X tweet id; next run requests tweets newer than this id.', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_post_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('text', models.TextField()),
                ('author_handle', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True, max_length=512)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.PositiveSmallIntegerField(blank=True, help_text='Integer 0–9 after successful analysis.', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, help_text='Model-reported confidence in [0, 1] when provided.', null=True)),
                ('analysis_error', models.TextField(blank=True, help_text='Last classification failure message (rate limits, invalid JSON, etc.).')),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
                'indexes': [models.Index(fields=['-analyzed_at'], name='tracker_soc_analyze_18575b_idx'), models.Index(fields=['sentiment_score', '-analyzed_at'], name='tracker_soc_sentime_2f7c64_idx')],
            },
        ),
    ]
